version: "3.9"
services:

  rabbitmq1:
    image: rabbitmq:3.9-management
    volumes:
      - /Users/pgadge/project/ApacheCamelDemo/camlvol:/home/cameldemo
    ports:
      - 15672:15672
      - 5672:5672


  camelApp:
   image: camelrabbitdemo:latest
   volumes:
    - /Users/pgadge/project/ApacheCamelDemo/camlvol:/home/cameldemo
   ports:
    - 8081:8080
   depends_on:
    - rabbitmq1

